run:
  timeout: 5m
  skip-files:
    - generated.*

issues:
  new: true
  exclude-rules:
    - linters:
      - staticcheck
      text: "SA1019:"

linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
  disable:
    - deadcode
    - errcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/v2fly/v2ray-core
