language: go
sudo: false

env:
  - GO111MODULE=on

go:
  - 1.11.x
  - 1.x

script:
  - go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
