name: Linter

on:
  push:
    branches:
      - master
      - v*
    paths:
      - "**/*.go"
      - ".github/workflows/linter.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.go"
      - ".github/workflows/linter.yml"

jobs:
  lint:
    if: github.repository == 'v2fly/v2ray-core'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          args: --config=.github/linters/.golangci.yml
          only-new-issues: true
