language: go

sudo: false

os:
  - linux
  - osx

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

script: 
 - go test -v -cpu=1,2,4 .
 - go test -v -cpu=2 -race -short .

matrix:
  allow_failures:
    - go: 'master'
  fast_finish: true 
